name: Trigger update to docs.pact.io


on: push
# on:
#   push:
#     branches:
#       - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Detect changes to markdown files
        id: detect-changed-markdown-files
        uses: bethtesque/has-changed-path@master
        with:
          paths: "*.md"

      - name: Trigger docs.pact.io update workflow
        if: steps.detect-changed-markdown-files.outputs.changed == 'true'
        run: |
          curl -X POST https://api.github.com/repos/pact-foundation/docs.pact.io/dispatches \
                -H 'Accept: application/vnd.github.everest-preview+json' \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -d '{"event_type": "pact-jvm-docs-updated"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENFORTRIGGERINGPACTDOCSUPDATE }}
